Add copy on start for automation blueprint dev
ludeeus/container pull request #169
Opened 2021-07-01 16:18 UTC by TheRealWaldo

@ludeeus Could not find any contribution guidelines, but please consider adding this.

I'm using your container for developing integrations on home assistant and found it also handy to use for blueprints.

Thanks for your contributions, and let me know if there is anything else I need to do!

2021-07-02 13:51 UTC, ludeeus requested changes
Why is this limited to automations?
Would it not make sense to copy the entire blueprint dir?

2021-07-02 13:51 UTC, ludeeus commented on rootfs/common/usr/share/container/start
> +    cp -r blueprints/automation/* /config/blueprints/automation/ || echo "Failed to copy automation blueprints"
Use `$(GetWorkspaceName).devcontainer/` like the others

2021-07-03 17:29 UTC, TheRealWaldo commented on rootfs/common/usr/share/container/start
> +    cp -r blueprints/automation/* /config/blueprints/automation/ || echo "Failed to copy automation blueprints"
> Use `$(GetWorkspaceName).devcontainer/` like the others

I noticed that the others are symlinks that require the full path, but the test comparisons are relative.  A copy operation doesn't require the full path.

If the full path is required for the operation, shouldn't all of the comparisons be updated in the file as well?

2021-07-03 17:36 UTC, TheRealWaldo commented
> Why is this limited to automations?
> Would it not make sense to copy the entire blueprint dir?

I considered copying the whole blueprint folder, but as I'm not aware of its intended future, it could be premature optimization.  Happy to open it up if you think it's wise!

2021-07-04 07:54 UTC, ludeeus commented on rootfs/common/usr/share/container/start
> +    cp -r blueprints/automation/* /config/blueprints/automation/ || echo "Failed to copy automation blueprints"
absolute path will always work, relative will not work in all cases.

2021-07-04 07:55 UTC, ludeeus commented
You can already have blueprints/scripts, and more will probably come, so if this is added, it should be everything

2021-07-04 14:59 UTC, TheRealWaldo commented on rootfs/common/usr/share/container/start
> +    cp -r blueprints/automation/* /config/blueprints/automation/ || echo "Failed to copy automation blueprints"
In this case, it'd be redundant because the tests are relative... so should I submit a request with all the tests in this file set to absolute?

2021-08-12 08:03 UTC, ludeeus commented on rootfs/common/usr/share/container/start
> +    cp -r blueprints/automation/* /config/blueprints/automation/ || echo "Failed to copy automation blueprints"
Please do

2021-08-12 18:14 UTC, TheRealWaldo commented on rootfs/common/usr/share/container/start
> +    if test -d "/config/custom_components"; then
@ludeeus it looks like this was a bug; it was redundant checking the same path twice.  I assume the logic was supposed to check if the /config/custom_compnents existed and delete it.

2021-08-12 18:16 UTC, TheRealWaldo commented on rootfs/common/usr/share/container/start
> +    cp -r blueprints/automation/* /config/blueprints/automation/ || echo "Failed to copy automation blueprints"
Done.

2021-08-12 19:04 UTC, ludeeus commented on rootfs/common/usr/share/container/start
> +    if test -d "/config/custom_components"; then
That's correct :+1:

2021-10-02 08:52 UTC, ludeeus approved these changes

2021-10-02 08:52 UTC, merged