Allow users to run their own code as part of "Set Home Assistant Version" task.
ludeeus/container pull request #272
Opened 2022-04-16 21:10 UTC by elahd

Adds hook to "Set Home Assistant Version" script to allow users to add-on their own code. The set version script will run whatever code/script is defined as the POST_SET_VERSION_HOOK environment variable.

This addresses item 2 in #270 using a much more generic approach.

2022-04-16 23:23 UTC, elahd commented
For context, I use this feature as follows:

1) Added the below section to my project's devcontainer.json:

```json
  "containerEnv": {
    "POST_SET_VERSION_HOOK": "/workspaces/[projectname]/post-set-version-hook.sh"
  },
```

2) Contents of `post-set-version-hook.sh`, which accepts a Home Assistant version number as an input argument:

```bash
#!/usr/bin/env bash

git_dir="/tmp/ver"
dev_dir="/ha-dev"
repo_url="https://github.com/home-assistant/core.git"

if [ -z "$1" ]; then
    echo "No version supplied. Deleting existing development files."
    rm -rf $dev_dir/pylint
    exit 1
fi

mkdir -p "$git_dir"

if [ "$(git -C "$git_dir" config --get remote.origin.url)" == "$repo_url" ]; then
    git -C "$git_dir" checkout tags/"$1"
else
    git clone "$repo_url" --branch "$version" "$git_dir"
fi

mkdir -p "$dev_dir"

if [ "$(readlink "$dev_dir"/pylint)" != "$dev_dir"/pylint ]; then
    ln -sf /tmp/ver/pylint /ha-dev/pylint
fi
```

This script checks out the Home Assistant source code for the requested HA version and makes a specific folder available within `/ha-dev`.

2022-04-17 07:03 UTC, ludeeus requested changes

2022-04-17 07:03 UTC, ludeeus commented on container/helpers/common/homeassistant/set-version.sh
> +source /opt/container/helpers/common/paths.sh
```suggestion
```
Not needed

2022-04-17 07:03 UTC, ludeeus commented on container/helpers/common/paths.sh
> +    fi
```suggestion
```
Not needed

2022-04-17 07:03 UTC, ludeeus commented on container/helpers/common/homeassistant/set-version.sh
> +    "$(postSetVerionHook)" "$version"
```suggestion
if [[ -n "$POST_SET_VERSION_HOOK" ]]; then
    "$POST_SET_VERSION_HOOK" "$version"
```

2022-04-17 16:45 UTC, elahd commented
@ludeeus Thanks for the feedback. I made the changes and tested them locally.

2022-04-17 17:09 UTC, merged